baseURL = 'http://vinsflyfish.github.io/'
languageCode = "zh-cn"
title = "Lufy's Blog"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = ""
googleAnalytics = "UA-131330078-1" # google analytics
sectionPagesMenu = "main"
hasCJKLanguage = true
summaryLength = 300 

[menu]
[[menu.main]]
  name = '技术'
  title = '技术'
  identifier = 'posts'
  url = '/posts/'
  weight = -100
[[menu.main]]
  name = '想法'
  identifier = 'ideas'
  url = '/ideas/'
  weight = -90
[[menu.main]]
  name = '关于'
  identifier = 'about'
  url = '/about/'
  weight = -80

[Author] # Used in authorbox
    name = "Lufy"
    bio = "游戏后台开发，关注一点分布式系统，关注一点go~"
    avatar = "img/avatar.jpg"


[Params]
    subtitle = "独立的思考着，尝试着能看到一点点未来" # Subtitle of your site. Used in site header
    description = "记录一些杂乱的思考和总结" # Description of your site. Used in meta description
	copyright = "Lufy"
	schema = true
	toc = true
	pager = true
    opengraph = true # Enable OpenGraph if true
    readmore = true # Show "Read more" button in list if true
    authorbox = false # Show authorbox at bottom of pages if true
    dateformat = "2006-01-02" # change the format of dates
	mainSections = ["posts", "ideas"]
	post_meta = ["date", "categories"]

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
	recent_num = 10 # Set the number of articles in the "Recent articles" widget
	categories_counter = true # Enable counter for each category in "Categories" widget
	tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  github = "vinsflyfish"
  email = "vins.napoleon@gmail.com"

